project_id = "eoskcsbytaurtqrnuraw"

[functions.ai-assistant]
verify_jwt = true

[functions.send-email]
verify_jwt = true

[functions.generate-franchise-data]
verify_jwt = true

[functions.generate-code]
verify_jwt = true

[functions.lindy-webhook]
verify_jwt = false

[functions.redeem-gift-card]
verify_jwt = false

[functions.fulfill-order]
verify_jwt = true